# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# Oppdater med riktig informasjon
id: hl7.fhir.no.hackathon.2025
canonical: http://hl7.no/fhir/ig/hackathon/2025
name: FHIR Hackathon 2025
title: "FHIR Hackathon 2025"
description: Implementation guide to plan the event and document and publish results from Norwegian FHIR Hackathon 2025
status: draft
version: 1.4.4
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#NO "Norway"
# Oppdater navn og URL til din organisasjon
publisher:
  name: HL7 Norge
  url: https://www.hl7.no
#dependencies:
#  hl7.fhir.no.basis: 2.2.2

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Agenda: 
     Hackathon agenda: hack-agenda.html
     Startup meeting agenda: pre-agenda.html
  Results: 
    IG publishing results: ig-publishing-results.html
    PMD track results: resultater-pmd.html
    OKT track results: resultater-okt.html
  Tracks:
    Track descriptions: track-descriptions.html
    Nordic tx-fhir and terminology: terminology.html
    IG publishing: ig-publishing.html
  Practical: practical-info.html
  Next year: 2026-changes.html
  TOC: toc.html
